use crate::structs::Piece;

pub const PIECES: [Piece; 256] = [
    Piece {
        reid: 1,
        top: 1,
        right: 17,
        bottom: 0,
        left: 0,
    },
    Piece {
        reid: 2,
        top: 1,
        right: 5,
        bottom: 0,
        left: 0,
    },
    Piece {
        reid: 3,
        top: 9,
        right: 17,
        bottom: 0,
        left: 0,
    },
    Piece {
        reid: 4,
        top: 17,
        right: 9,
        bottom: 0,
        left: 0,
    },
    Piece {
        reid: 5,
        top: 2,
        right: 1,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 6,
        top: 10,
        right: 9,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 7,
        top: 6,
        right: 1,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 8,
        top: 6,
        right: 13,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 9,
        top: 11,
        right: 17,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 10,
        top: 7,
        right: 5,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 11,
        top: 15,
        right: 9,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 12,
        top: 8,
        right: 5,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 13,
        top: 8,
        right: 13,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 14,
        top: 21,
        right: 5,
        bottom: 0,
        left: 1,
    },
    Piece {
        reid: 15,
        top: 10,
        right: 1,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 16,
        top: 18,
        right: 17,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 17,
        top: 14,
        right: 13,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 18,
        top: 19,
        right: 13,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 19,
        top: 7,
        right: 9,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 20,
        top: 15,
        right: 9,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 21,
        top: 4,
        right: 5,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 22,
        top: 12,
        right: 1,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 23,
        top: 12,
        right: 13,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 24,
        top: 20,
        right: 1,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 25,
        top: 21,
        right: 1,
        bottom: 0,
        left: 9,
    },
    Piece {
        reid: 26,
        top: 2,
        right: 9,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 27,
        top: 2,
        right: 17,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 28,
        top: 10,
        right: 17,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 29,
        top: 18,
        right: 17,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 30,
        top: 7,
        right: 13,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 31,
        top: 15,
        right: 9,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 32,
        top: 20,
        right: 17,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 33,
        top: 8,
        right: 9,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 34,
        top: 8,
        right: 5,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 35,
        top: 16,
        right: 13,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 36,
        top: 22,
        right: 5,
        bottom: 0,
        left: 17,
    },
    Piece {
        reid: 37,
        top: 18,
        right: 1,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 38,
        top: 3,
        right: 13,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 39,
        top: 11,
        right: 13,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 40,
        top: 19,
        right: 9,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 41,
        top: 19,
        right: 17,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 42,
        top: 15,
        right: 1,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 43,
        top: 15,
        right: 9,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 44,
        top: 15,
        right: 17,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 45,
        top: 4,
        right: 1,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 46,
        top: 20,
        right: 5,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 47,
        top: 8,
        right: 5,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 48,
        top: 16,
        right: 5,
        bottom: 0,
        left: 5,
    },
    Piece {
        reid: 49,
        top: 2,
        right: 13,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 50,
        top: 10,
        right: 1,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 51,
        top: 10,
        right: 9,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 52,
        top: 6,
        right: 1,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 53,
        top: 7,
        right: 5,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 54,
        top: 4,
        right: 5,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 55,
        top: 4,
        right: 13,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 56,
        top: 8,
        right: 17,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 57,
        top: 16,
        right: 1,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 58,
        top: 16,
        right: 13,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 59,
        top: 21,
        right: 9,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 60,
        top: 22,
        right: 17,
        bottom: 0,
        left: 13,
    },
    Piece {
        reid: 61,
        top: 6,
        right: 18,
        bottom: 2,
        left: 2,
    },
    Piece {
        reid: 62,
        top: 14,
        right: 7,
        bottom: 2,
        left: 2,
    },
    Piece {
        reid: 63,
        top: 10,
        right: 3,
        bottom: 2,
        left: 10,
    },
    Piece {
        reid: 64,
        top: 2,
        right: 8,
        bottom: 2,
        left: 18,
    },
    Piece {
        reid: 65,
        top: 18,
        right: 22,
        bottom: 2,
        left: 18,
    },
    Piece {
        reid: 66,
        top: 14,
        right: 14,
        bottom: 2,
        left: 18,
    },
    Piece {
        reid: 67,
        top: 11,
        right: 10,
        bottom: 2,
        left: 18,
    },
    Piece {
        reid: 68,
        top: 20,
        right: 6,
        bottom: 2,
        left: 18,
    },
    Piece {
        reid: 69,
        top: 22,
        right: 8,
        bottom: 2,
        left: 18,
    },
    Piece {
        reid: 70,
        top: 3,
        right: 7,
        bottom: 2,
        left: 3,
    },
    Piece {
        reid: 71,
        top: 7,
        right: 12,
        bottom: 2,
        left: 3,
    },
    Piece {
        reid: 72,
        top: 14,
        right: 18,
        bottom: 2,
        left: 11,
    },
    Piece {
        reid: 73,
        top: 15,
        right: 4,
        bottom: 2,
        left: 11,
    },
    Piece {
        reid: 74,
        top: 20,
        right: 15,
        bottom: 2,
        left: 11,
    },
    Piece {
        reid: 75,
        top: 8,
        right: 3,
        bottom: 2,
        left: 11,
    },
    Piece {
        reid: 76,
        top: 14,
        right: 15,
        bottom: 2,
        left: 19,
    },
    Piece {
        reid: 77,
        top: 19,
        right: 15,
        bottom: 2,
        left: 19,
    },
    Piece {
        reid: 78,
        top: 3,
        right: 16,
        bottom: 2,
        left: 7,
    },
    Piece {
        reid: 79,
        top: 20,
        right: 3,
        bottom: 2,
        left: 7,
    },
    Piece {
        reid: 80,
        top: 16,
        right: 21,
        bottom: 2,
        left: 7,
    },
    Piece {
        reid: 81,
        top: 19,
        right: 18,
        bottom: 2,
        left: 15,
    },
    Piece {
        reid: 82,
        top: 18,
        right: 18,
        bottom: 2,
        left: 4,
    },
    Piece {
        reid: 83,
        top: 11,
        right: 4,
        bottom: 2,
        left: 4,
    },
    Piece {
        reid: 84,
        top: 18,
        right: 19,
        bottom: 2,
        left: 12,
    },
    Piece {
        reid: 85,
        top: 6,
        right: 14,
        bottom: 2,
        left: 12,
    },
    Piece {
        reid: 86,
        top: 8,
        right: 12,
        bottom: 2,
        left: 12,
    },
    Piece {
        reid: 87,
        top: 16,
        right: 20,
        bottom: 2,
        left: 12,
    },
    Piece {
        reid: 88,
        top: 2,
        right: 21,
        bottom: 2,
        left: 20,
    },
    Piece {
        reid: 89,
        top: 6,
        right: 22,
        bottom: 2,
        left: 20,
    },
    Piece {
        reid: 90,
        top: 4,
        right: 16,
        bottom: 2,
        left: 20,
    },
    Piece {
        reid: 91,
        top: 11,
        right: 12,
        bottom: 2,
        left: 8,
    },
    Piece {
        reid: 92,
        top: 19,
        right: 15,
        bottom: 2,
        left: 8,
    },
    Piece {
        reid: 93,
        top: 19,
        right: 4,
        bottom: 2,
        left: 8,
    },
    Piece {
        reid: 94,
        top: 4,
        right: 21,
        bottom: 2,
        left: 8,
    },
    Piece {
        reid: 95,
        top: 12,
        right: 14,
        bottom: 2,
        left: 8,
    },
    Piece {
        reid: 96,
        top: 21,
        right: 3,
        bottom: 2,
        left: 21,
    },
    Piece {
        reid: 97,
        top: 4,
        right: 19,
        bottom: 2,
        left: 22,
    },
    Piece {
        reid: 98,
        top: 20,
        right: 8,
        bottom: 2,
        left: 22,
    },
    Piece {
        reid: 99,
        top: 21,
        right: 6,
        bottom: 2,
        left: 22,
    },
    Piece {
        reid: 100,
        top: 22,
        right: 21,
        bottom: 2,
        left: 22,
    },
    Piece {
        reid: 101,
        top: 12,
        right: 15,
        bottom: 10,
        left: 10,
    },
    Piece {
        reid: 102,
        top: 12,
        right: 16,
        bottom: 10,
        left: 10,
    },
    Piece {
        reid: 103,
        top: 16,
        right: 19,
        bottom: 10,
        left: 10,
    },
    Piece {
        reid: 104,
        top: 22,
        right: 6,
        bottom: 10,
        left: 10,
    },
    Piece {
        reid: 105,
        top: 4,
        right: 15,
        bottom: 10,
        left: 18,
    },
    Piece {
        reid: 106,
        top: 3,
        right: 8,
        bottom: 10,
        left: 6,
    },
    Piece {
        reid: 107,
        top: 19,
        right: 8,
        bottom: 10,
        left: 6,
    },
    Piece {
        reid: 108,
        top: 4,
        right: 15,
        bottom: 10,
        left: 6,
    },
    Piece {
        reid: 109,
        top: 16,
        right: 11,
        bottom: 10,
        left: 6,
    },
    Piece {
        reid: 110,
        top: 15,
        right: 12,
        bottom: 10,
        left: 14,
    },
    Piece {
        reid: 111,
        top: 12,
        right: 15,
        bottom: 10,
        left: 14,
    },
    Piece {
        reid: 112,
        top: 20,
        right: 19,
        bottom: 10,
        left: 3,
    },
    Piece {
        reid: 113,
        top: 20,
        right: 16,
        bottom: 10,
        left: 3,
    },
    Piece {
        reid: 114,
        top: 14,
        right: 4,
        bottom: 10,
        left: 11,
    },
    Piece {
        reid: 115,
        top: 7,
        right: 12,
        bottom: 10,
        left: 11,
    },
    Piece {
        reid: 116,
        top: 12,
        right: 11,
        bottom: 10,
        left: 11,
    },
    Piece {
        reid: 117,
        top: 22,
        right: 16,
        bottom: 10,
        left: 11,
    },
    Piece {
        reid: 118,
        top: 3,
        right: 21,
        bottom: 10,
        left: 19,
    },
    Piece {
        reid: 119,
        top: 16,
        right: 12,
        bottom: 10,
        left: 7,
    },
    Piece {
        reid: 120,
        top: 8,
        right: 22,
        bottom: 10,
        left: 15,
    },
    Piece {
        reid: 121,
        top: 14,
        right: 22,
        bottom: 10,
        left: 4,
    },
    Piece {
        reid: 122,
        top: 6,
        right: 16,
        bottom: 10,
        left: 20,
    },
    Piece {
        reid: 123,
        top: 14,
        right: 19,
        bottom: 10,
        left: 20,
    },
    Piece {
        reid: 124,
        top: 20,
        right: 15,
        bottom: 10,
        left: 20,
    },
    Piece {
        reid: 125,
        top: 12,
        right: 22,
        bottom: 10,
        left: 8,
    },
    Piece {
        reid: 126,
        top: 21,
        right: 15,
        bottom: 10,
        left: 8,
    },
    Piece {
        reid: 127,
        top: 14,
        right: 6,
        bottom: 10,
        left: 16,
    },
    Piece {
        reid: 128,
        top: 19,
        right: 21,
        bottom: 10,
        left: 16,
    },
    Piece {
        reid: 129,
        top: 4,
        right: 3,
        bottom: 10,
        left: 16,
    },
    Piece {
        reid: 130,
        top: 20,
        right: 8,
        bottom: 10,
        left: 16,
    },
    Piece {
        reid: 131,
        top: 6,
        right: 20,
        bottom: 10,
        left: 21,
    },
    Piece {
        reid: 132,
        top: 12,
        right: 14,
        bottom: 10,
        left: 21,
    },
    Piece {
        reid: 133,
        top: 14,
        right: 16,
        bottom: 10,
        left: 22,
    },
    Piece {
        reid: 134,
        top: 11,
        right: 4,
        bottom: 10,
        left: 22,
    },
    Piece {
        reid: 135,
        top: 4,
        right: 3,
        bottom: 10,
        left: 22,
    },
    Piece {
        reid: 136,
        top: 16,
        right: 20,
        bottom: 10,
        left: 22,
    },
    Piece {
        reid: 137,
        top: 20,
        right: 7,
        bottom: 18,
        left: 18,
    },
    Piece {
        reid: 138,
        top: 6,
        right: 3,
        bottom: 18,
        left: 6,
    },
    Piece {
        reid: 139,
        top: 6,
        right: 11,
        bottom: 18,
        left: 6,
    },
    Piece {
        reid: 140,
        top: 6,
        right: 12,
        bottom: 18,
        left: 6,
    },
    Piece {
        reid: 141,
        top: 19,
        right: 21,
        bottom: 18,
        left: 6,
    },
    Piece {
        reid: 142,
        top: 15,
        right: 6,
        bottom: 18,
        left: 6,
    },
    Piece {
        reid: 143,
        top: 16,
        right: 12,
        bottom: 18,
        left: 6,
    },
    Piece {
        reid: 144,
        top: 21,
        right: 21,
        bottom: 18,
        left: 6,
    },
    Piece {
        reid: 145,
        top: 3,
        right: 4,
        bottom: 18,
        left: 14,
    },
    Piece {
        reid: 146,
        top: 18,
        right: 12,
        bottom: 18,
        left: 3,
    },
    Piece {
        reid: 147,
        top: 18,
        right: 22,
        bottom: 18,
        left: 3,
    },
    Piece {
        reid: 148,
        top: 3,
        right: 14,
        bottom: 18,
        left: 3,
    },
    Piece {
        reid: 149,
        top: 15,
        right: 12,
        bottom: 18,
        left: 3,
    },
    Piece {
        reid: 150,
        top: 6,
        right: 11,
        bottom: 18,
        left: 19,
    },
    Piece {
        reid: 151,
        top: 4,
        right: 22,
        bottom: 18,
        left: 19,
    },
    Piece {
        reid: 152,
        top: 11,
        right: 11,
        bottom: 18,
        left: 7,
    },
    Piece {
        reid: 153,
        top: 11,
        right: 19,
        bottom: 18,
        left: 7,
    },
    Piece {
        reid: 154,
        top: 22,
        right: 16,
        bottom: 18,
        left: 7,
    },
    Piece {
        reid: 155,
        top: 7,
        right: 7,
        bottom: 18,
        left: 4,
    },
    Piece {
        reid: 156,
        top: 7,
        right: 12,
        bottom: 18,
        left: 4,
    },
    Piece {
        reid: 157,
        top: 22,
        right: 7,
        bottom: 18,
        left: 4,
    },
    Piece {
        reid: 158,
        top: 7,
        right: 16,
        bottom: 18,
        left: 20,
    },
    Piece {
        reid: 159,
        top: 8,
        right: 6,
        bottom: 18,
        left: 20,
    },
    Piece {
        reid: 160,
        top: 21,
        right: 21,
        bottom: 18,
        left: 8,
    },
    Piece {
        reid: 161,
        top: 6,
        right: 20,
        bottom: 18,
        left: 16,
    },
    Piece {
        reid: 162,
        top: 14,
        right: 20,
        bottom: 18,
        left: 16,
    },
    Piece {
        reid: 163,
        top: 15,
        right: 11,
        bottom: 18,
        left: 22,
    },
    Piece {
        reid: 164,
        top: 4,
        right: 16,
        bottom: 18,
        left: 22,
    },
    Piece {
        reid: 165,
        top: 3,
        right: 4,
        bottom: 6,
        left: 14,
    },
    Piece {
        reid: 166,
        top: 4,
        right: 8,
        bottom: 6,
        left: 14,
    },
    Piece {
        reid: 167,
        top: 3,
        right: 3,
        bottom: 6,
        left: 11,
    },
    Piece {
        reid: 168,
        top: 11,
        right: 15,
        bottom: 6,
        left: 19,
    },
    Piece {
        reid: 169,
        top: 19,
        right: 21,
        bottom: 6,
        left: 19,
    },
    Piece {
        reid: 170,
        top: 4,
        right: 8,
        bottom: 6,
        left: 7,
    },
    Piece {
        reid: 171,
        top: 20,
        right: 16,
        bottom: 6,
        left: 7,
    },
    Piece {
        reid: 172,
        top: 21,
        right: 11,
        bottom: 6,
        left: 7,
    },
    Piece {
        reid: 173,
        top: 15,
        right: 15,
        bottom: 6,
        left: 15,
    },
    Piece {
        reid: 174,
        top: 12,
        right: 20,
        bottom: 6,
        left: 15,
    },
    Piece {
        reid: 175,
        top: 7,
        right: 21,
        bottom: 6,
        left: 4,
    },
    Piece {
        reid: 176,
        top: 7,
        right: 19,
        bottom: 6,
        left: 12,
    },
    Piece {
        reid: 177,
        top: 14,
        right: 4,
        bottom: 6,
        left: 20,
    },
    Piece {
        reid: 178,
        top: 12,
        right: 16,
        bottom: 6,
        left: 8,
    },
    Piece {
        reid: 179,
        top: 8,
        right: 15,
        bottom: 6,
        left: 8,
    },
    Piece {
        reid: 180,
        top: 7,
        right: 16,
        bottom: 6,
        left: 16,
    },
    Piece {
        reid: 181,
        top: 11,
        right: 16,
        bottom: 6,
        left: 21,
    },
    Piece {
        reid: 182,
        top: 7,
        right: 11,
        bottom: 6,
        left: 21,
    },
    Piece {
        reid: 183,
        top: 19,
        right: 8,
        bottom: 14,
        left: 14,
    },
    Piece {
        reid: 184,
        top: 22,
        right: 7,
        bottom: 14,
        left: 3,
    },
    Piece {
        reid: 185,
        top: 19,
        right: 12,
        bottom: 14,
        left: 11,
    },
    Piece {
        reid: 186,
        top: 8,
        right: 8,
        bottom: 14,
        left: 11,
    },
    Piece {
        reid: 187,
        top: 21,
        right: 7,
        bottom: 14,
        left: 19,
    },
    Piece {
        reid: 188,
        top: 14,
        right: 21,
        bottom: 14,
        left: 7,
    },
    Piece {
        reid: 189,
        top: 3,
        right: 19,
        bottom: 14,
        left: 7,
    },
    Piece {
        reid: 190,
        top: 16,
        right: 19,
        bottom: 14,
        left: 7,
    },
    Piece {
        reid: 191,
        top: 3,
        right: 3,
        bottom: 14,
        left: 15,
    },
    Piece {
        reid: 192,
        top: 15,
        right: 20,
        bottom: 14,
        left: 15,
    },
    Piece {
        reid: 193,
        top: 11,
        right: 7,
        bottom: 14,
        left: 4,
    },
    Piece {
        reid: 194,
        top: 21,
        right: 11,
        bottom: 14,
        left: 12,
    },
    Piece {
        reid: 195,
        top: 21,
        right: 22,
        bottom: 14,
        left: 12,
    },
    Piece {
        reid: 196,
        top: 22,
        right: 15,
        bottom: 14,
        left: 12,
    },
    Piece {
        reid: 197,
        top: 11,
        right: 22,
        bottom: 14,
        left: 20,
    },
    Piece {
        reid: 198,
        top: 19,
        right: 8,
        bottom: 14,
        left: 20,
    },
    Piece {
        reid: 199,
        top: 20,
        right: 20,
        bottom: 14,
        left: 20,
    },
    Piece {
        reid: 200,
        top: 19,
        right: 3,
        bottom: 14,
        left: 8,
    },
    Piece {
        reid: 201,
        top: 21,
        right: 8,
        bottom: 14,
        left: 16,
    },
    Piece {
        reid: 202,
        top: 22,
        right: 7,
        bottom: 14,
        left: 16,
    },
    Piece {
        reid: 203,
        top: 12,
        right: 19,
        bottom: 14,
        left: 21,
    },
    Piece {
        reid: 204,
        top: 12,
        right: 8,
        bottom: 14,
        left: 21,
    },
    Piece {
        reid: 205,
        top: 16,
        right: 3,
        bottom: 14,
        left: 21,
    },
    Piece {
        reid: 206,
        top: 22,
        right: 21,
        bottom: 14,
        left: 21,
    },
    Piece {
        reid: 207,
        top: 22,
        right: 7,
        bottom: 3,
        left: 3,
    },
    Piece {
        reid: 208,
        top: 19,
        right: 22,
        bottom: 3,
        left: 11,
    },
    Piece {
        reid: 209,
        top: 8,
        right: 15,
        bottom: 3,
        left: 11,
    },
    Piece {
        reid: 210,
        top: 11,
        right: 19,
        bottom: 3,
        left: 7,
    },
    Piece {
        reid: 211,
        top: 16,
        right: 15,
        bottom: 3,
        left: 7,
    },
    Piece {
        reid: 212,
        top: 3,
        right: 16,
        bottom: 3,
        left: 15,
    },
    Piece {
        reid: 213,
        top: 8,
        right: 8,
        bottom: 3,
        left: 4,
    },
    Piece {
        reid: 214,
        top: 3,
        right: 20,
        bottom: 3,
        left: 12,
    },
    Piece {
        reid: 215,
        top: 4,
        right: 22,
        bottom: 3,
        left: 12,
    },
    Piece {
        reid: 216,
        top: 22,
        right: 21,
        bottom: 3,
        left: 12,
    },
    Piece {
        reid: 217,
        top: 19,
        right: 15,
        bottom: 3,
        left: 20,
    },
    Piece {
        reid: 218,
        top: 4,
        right: 12,
        bottom: 3,
        left: 16,
    },
    Piece {
        reid: 219,
        top: 11,
        right: 4,
        bottom: 3,
        left: 21,
    },
    Piece {
        reid: 220,
        top: 11,
        right: 16,
        bottom: 3,
        left: 22,
    },
    Piece {
        reid: 221,
        top: 21,
        right: 21,
        bottom: 3,
        left: 22,
    },
    Piece {
        reid: 222,
        top: 21,
        right: 22,
        bottom: 3,
        left: 22,
    },
    Piece {
        reid: 223,
        top: 12,
        right: 22,
        bottom: 11,
        left: 11,
    },
    Piece {
        reid: 224,
        top: 20,
        right: 7,
        bottom: 11,
        left: 11,
    },
    Piece {
        reid: 225,
        top: 16,
        right: 15,
        bottom: 11,
        left: 11,
    },
    Piece {
        reid: 226,
        top: 19,
        right: 15,
        bottom: 11,
        left: 7,
    },
    Piece {
        reid: 227,
        top: 12,
        right: 12,
        bottom: 11,
        left: 7,
    },
    Piece {
        reid: 228,
        top: 19,
        right: 8,
        bottom: 11,
        left: 4,
    },
    Piece {
        reid: 229,
        top: 7,
        right: 22,
        bottom: 11,
        left: 20,
    },
    Piece {
        reid: 230,
        top: 16,
        right: 8,
        bottom: 11,
        left: 20,
    },
    Piece {
        reid: 231,
        top: 12,
        right: 20,
        bottom: 11,
        left: 8,
    },
    Piece {
        reid: 232,
        top: 12,
        right: 21,
        bottom: 11,
        left: 8,
    },
    Piece {
        reid: 233,
        top: 19,
        right: 20,
        bottom: 19,
        left: 19,
    },
    Piece {
        reid: 234,
        top: 16,
        right: 4,
        bottom: 19,
        left: 7,
    },
    Piece {
        reid: 235,
        top: 7,
        right: 4,
        bottom: 19,
        left: 4,
    },
    Piece {
        reid: 236,
        top: 7,
        right: 20,
        bottom: 19,
        left: 4,
    },
    Piece {
        reid: 237,
        top: 12,
        right: 15,
        bottom: 19,
        left: 4,
    },
    Piece {
        reid: 238,
        top: 4,
        right: 16,
        bottom: 19,
        left: 12,
    },
    Piece {
        reid: 239,
        top: 15,
        right: 22,
        bottom: 19,
        left: 20,
    },
    Piece {
        reid: 240,
        top: 21,
        right: 15,
        bottom: 19,
        left: 20,
    },
    Piece {
        reid: 241,
        top: 7,
        right: 21,
        bottom: 19,
        left: 8,
    },
    Piece {
        reid: 242,
        top: 4,
        right: 21,
        bottom: 19,
        left: 8,
    },
    Piece {
        reid: 243,
        top: 15,
        right: 12,
        bottom: 7,
        left: 15,
    },
    Piece {
        reid: 244,
        top: 20,
        right: 8,
        bottom: 7,
        left: 15,
    },
    Piece {
        reid: 245,
        top: 22,
        right: 20,
        bottom: 7,
        left: 4,
    },
    Piece {
        reid: 246,
        top: 16,
        right: 22,
        bottom: 7,
        left: 21,
    },
    Piece {
        reid: 247,
        top: 21,
        right: 22,
        bottom: 15,
        left: 15,
    },
    Piece {
        reid: 248,
        top: 12,
        right: 4,
        bottom: 15,
        left: 4,
    },
    Piece {
        reid: 249,
        top: 4,
        right: 21,
        bottom: 15,
        left: 12,
    },
    Piece {
        reid: 250,
        top: 16,
        right: 21,
        bottom: 15,
        left: 20,
    },
    Piece {
        reid: 251,
        top: 22,
        right: 8,
        bottom: 4,
        left: 4,
    },
    Piece {
        reid: 252,
        top: 8,
        right: 12,
        bottom: 4,
        left: 12,
    },
    Piece {
        reid: 253,
        top: 16,
        right: 20,
        bottom: 12,
        left: 8,
    },
    Piece {
        reid: 254,
        top: 21,
        right: 16,
        bottom: 20,
        left: 16,
    },
    Piece {
        reid: 255,
        top: 16,
        right: 22,
        bottom: 20,
        left: 22,
    },
    Piece {
        reid: 256,
        top: 21,
        right: 22,
        bottom: 8,
        left: 22,
    },
];
