use crate::structs::Piece;

pub const PIECES: [Piece; 256] = [
    Piece {
        piece_number: 1,
        top_side: 1,
        right_side: 17,
        bottom_side: 0,
        left_side: 0,
    },
    Piece {
        piece_number: 2,
        top_side: 1,
        right_side: 5,
        bottom_side: 0,
        left_side: 0,
    },
    Piece {
        piece_number: 3,
        top_side: 9,
        right_side: 17,
        bottom_side: 0,
        left_side: 0,
    },
    Piece {
        piece_number: 4,
        top_side: 17,
        right_side: 9,
        bottom_side: 0,
        left_side: 0,
    },
    Piece {
        piece_number: 5,
        top_side: 2,
        right_side: 1,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 6,
        top_side: 10,
        right_side: 9,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 7,
        top_side: 6,
        right_side: 1,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 8,
        top_side: 6,
        right_side: 13,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 9,
        top_side: 11,
        right_side: 17,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 10,
        top_side: 7,
        right_side: 5,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 11,
        top_side: 15,
        right_side: 9,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 12,
        top_side: 8,
        right_side: 5,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 13,
        top_side: 8,
        right_side: 13,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 14,
        top_side: 21,
        right_side: 5,
        bottom_side: 0,
        left_side: 1,
    },
    Piece {
        piece_number: 15,
        top_side: 10,
        right_side: 1,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 16,
        top_side: 18,
        right_side: 17,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 17,
        top_side: 14,
        right_side: 13,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 18,
        top_side: 19,
        right_side: 13,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 19,
        top_side: 7,
        right_side: 9,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 20,
        top_side: 15,
        right_side: 9,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 21,
        top_side: 4,
        right_side: 5,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 22,
        top_side: 12,
        right_side: 1,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 23,
        top_side: 12,
        right_side: 13,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 24,
        top_side: 20,
        right_side: 1,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 25,
        top_side: 21,
        right_side: 1,
        bottom_side: 0,
        left_side: 9,
    },
    Piece {
        piece_number: 26,
        top_side: 2,
        right_side: 9,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 27,
        top_side: 2,
        right_side: 17,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 28,
        top_side: 10,
        right_side: 17,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 29,
        top_side: 18,
        right_side: 17,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 30,
        top_side: 7,
        right_side: 13,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 31,
        top_side: 15,
        right_side: 9,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 32,
        top_side: 20,
        right_side: 17,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 33,
        top_side: 8,
        right_side: 9,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 34,
        top_side: 8,
        right_side: 5,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 35,
        top_side: 16,
        right_side: 13,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 36,
        top_side: 22,
        right_side: 5,
        bottom_side: 0,
        left_side: 17,
    },
    Piece {
        piece_number: 37,
        top_side: 18,
        right_side: 1,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 38,
        top_side: 3,
        right_side: 13,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 39,
        top_side: 11,
        right_side: 13,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 40,
        top_side: 19,
        right_side: 9,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 41,
        top_side: 19,
        right_side: 17,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 42,
        top_side: 15,
        right_side: 1,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 43,
        top_side: 15,
        right_side: 9,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 44,
        top_side: 15,
        right_side: 17,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 45,
        top_side: 4,
        right_side: 1,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 46,
        top_side: 20,
        right_side: 5,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 47,
        top_side: 8,
        right_side: 5,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 48,
        top_side: 16,
        right_side: 5,
        bottom_side: 0,
        left_side: 5,
    },
    Piece {
        piece_number: 49,
        top_side: 2,
        right_side: 13,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 50,
        top_side: 10,
        right_side: 1,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 51,
        top_side: 10,
        right_side: 9,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 52,
        top_side: 6,
        right_side: 1,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 53,
        top_side: 7,
        right_side: 5,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 54,
        top_side: 4,
        right_side: 5,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 55,
        top_side: 4,
        right_side: 13,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 56,
        top_side: 8,
        right_side: 17,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 57,
        top_side: 16,
        right_side: 1,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 58,
        top_side: 16,
        right_side: 13,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 59,
        top_side: 21,
        right_side: 9,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 60,
        top_side: 22,
        right_side: 17,
        bottom_side: 0,
        left_side: 13,
    },
    Piece {
        piece_number: 61,
        top_side: 6,
        right_side: 18,
        bottom_side: 2,
        left_side: 2,
    },
    Piece {
        piece_number: 62,
        top_side: 14,
        right_side: 7,
        bottom_side: 2,
        left_side: 2,
    },
    Piece {
        piece_number: 63,
        top_side: 10,
        right_side: 3,
        bottom_side: 2,
        left_side: 10,
    },
    Piece {
        piece_number: 64,
        top_side: 2,
        right_side: 8,
        bottom_side: 2,
        left_side: 18,
    },
    Piece {
        piece_number: 65,
        top_side: 18,
        right_side: 22,
        bottom_side: 2,
        left_side: 18,
    },
    Piece {
        piece_number: 66,
        top_side: 14,
        right_side: 14,
        bottom_side: 2,
        left_side: 18,
    },
    Piece {
        piece_number: 67,
        top_side: 11,
        right_side: 10,
        bottom_side: 2,
        left_side: 18,
    },
    Piece {
        piece_number: 68,
        top_side: 20,
        right_side: 6,
        bottom_side: 2,
        left_side: 18,
    },
    Piece {
        piece_number: 69,
        top_side: 22,
        right_side: 8,
        bottom_side: 2,
        left_side: 18,
    },
    Piece {
        piece_number: 70,
        top_side: 3,
        right_side: 7,
        bottom_side: 2,
        left_side: 3,
    },
    Piece {
        piece_number: 71,
        top_side: 7,
        right_side: 12,
        bottom_side: 2,
        left_side: 3,
    },
    Piece {
        piece_number: 72,
        top_side: 14,
        right_side: 18,
        bottom_side: 2,
        left_side: 11,
    },
    Piece {
        piece_number: 73,
        top_side: 15,
        right_side: 4,
        bottom_side: 2,
        left_side: 11,
    },
    Piece {
        piece_number: 74,
        top_side: 20,
        right_side: 15,
        bottom_side: 2,
        left_side: 11,
    },
    Piece {
        piece_number: 75,
        top_side: 8,
        right_side: 3,
        bottom_side: 2,
        left_side: 11,
    },
    Piece {
        piece_number: 76,
        top_side: 14,
        right_side: 15,
        bottom_side: 2,
        left_side: 19,
    },
    Piece {
        piece_number: 77,
        top_side: 19,
        right_side: 15,
        bottom_side: 2,
        left_side: 19,
    },
    Piece {
        piece_number: 78,
        top_side: 3,
        right_side: 16,
        bottom_side: 2,
        left_side: 7,
    },
    Piece {
        piece_number: 79,
        top_side: 20,
        right_side: 3,
        bottom_side: 2,
        left_side: 7,
    },
    Piece {
        piece_number: 80,
        top_side: 16,
        right_side: 21,
        bottom_side: 2,
        left_side: 7,
    },
    Piece {
        piece_number: 81,
        top_side: 19,
        right_side: 18,
        bottom_side: 2,
        left_side: 15,
    },
    Piece {
        piece_number: 82,
        top_side: 18,
        right_side: 18,
        bottom_side: 2,
        left_side: 4,
    },
    Piece {
        piece_number: 83,
        top_side: 11,
        right_side: 4,
        bottom_side: 2,
        left_side: 4,
    },
    Piece {
        piece_number: 84,
        top_side: 18,
        right_side: 19,
        bottom_side: 2,
        left_side: 12,
    },
    Piece {
        piece_number: 85,
        top_side: 6,
        right_side: 14,
        bottom_side: 2,
        left_side: 12,
    },
    Piece {
        piece_number: 86,
        top_side: 8,
        right_side: 12,
        bottom_side: 2,
        left_side: 12,
    },
    Piece {
        piece_number: 87,
        top_side: 16,
        right_side: 20,
        bottom_side: 2,
        left_side: 12,
    },
    Piece {
        piece_number: 88,
        top_side: 2,
        right_side: 21,
        bottom_side: 2,
        left_side: 20,
    },
    Piece {
        piece_number: 89,
        top_side: 6,
        right_side: 22,
        bottom_side: 2,
        left_side: 20,
    },
    Piece {
        piece_number: 90,
        top_side: 4,
        right_side: 16,
        bottom_side: 2,
        left_side: 20,
    },
    Piece {
        piece_number: 91,
        top_side: 11,
        right_side: 12,
        bottom_side: 2,
        left_side: 8,
    },
    Piece {
        piece_number: 92,
        top_side: 19,
        right_side: 15,
        bottom_side: 2,
        left_side: 8,
    },
    Piece {
        piece_number: 93,
        top_side: 19,
        right_side: 4,
        bottom_side: 2,
        left_side: 8,
    },
    Piece {
        piece_number: 94,
        top_side: 4,
        right_side: 21,
        bottom_side: 2,
        left_side: 8,
    },
    Piece {
        piece_number: 95,
        top_side: 12,
        right_side: 14,
        bottom_side: 2,
        left_side: 8,
    },
    Piece {
        piece_number: 96,
        top_side: 21,
        right_side: 3,
        bottom_side: 2,
        left_side: 21,
    },
    Piece {
        piece_number: 97,
        top_side: 4,
        right_side: 19,
        bottom_side: 2,
        left_side: 22,
    },
    Piece {
        piece_number: 98,
        top_side: 20,
        right_side: 8,
        bottom_side: 2,
        left_side: 22,
    },
    Piece {
        piece_number: 99,
        top_side: 21,
        right_side: 6,
        bottom_side: 2,
        left_side: 22,
    },
    Piece {
        piece_number: 100,
        top_side: 22,
        right_side: 21,
        bottom_side: 2,
        left_side: 22,
    },
    Piece {
        piece_number: 101,
        top_side: 12,
        right_side: 15,
        bottom_side: 10,
        left_side: 10,
    },
    Piece {
        piece_number: 102,
        top_side: 12,
        right_side: 16,
        bottom_side: 10,
        left_side: 10,
    },
    Piece {
        piece_number: 103,
        top_side: 16,
        right_side: 19,
        bottom_side: 10,
        left_side: 10,
    },
    Piece {
        piece_number: 104,
        top_side: 22,
        right_side: 6,
        bottom_side: 10,
        left_side: 10,
    },
    Piece {
        piece_number: 105,
        top_side: 4,
        right_side: 15,
        bottom_side: 10,
        left_side: 18,
    },
    Piece {
        piece_number: 106,
        top_side: 3,
        right_side: 8,
        bottom_side: 10,
        left_side: 6,
    },
    Piece {
        piece_number: 107,
        top_side: 19,
        right_side: 8,
        bottom_side: 10,
        left_side: 6,
    },
    Piece {
        piece_number: 108,
        top_side: 4,
        right_side: 15,
        bottom_side: 10,
        left_side: 6,
    },
    Piece {
        piece_number: 109,
        top_side: 16,
        right_side: 11,
        bottom_side: 10,
        left_side: 6,
    },
    Piece {
        piece_number: 110,
        top_side: 15,
        right_side: 12,
        bottom_side: 10,
        left_side: 14,
    },
    Piece {
        piece_number: 111,
        top_side: 12,
        right_side: 15,
        bottom_side: 10,
        left_side: 14,
    },
    Piece {
        piece_number: 112,
        top_side: 20,
        right_side: 19,
        bottom_side: 10,
        left_side: 3,
    },
    Piece {
        piece_number: 113,
        top_side: 20,
        right_side: 16,
        bottom_side: 10,
        left_side: 3,
    },
    Piece {
        piece_number: 114,
        top_side: 14,
        right_side: 4,
        bottom_side: 10,
        left_side: 11,
    },
    Piece {
        piece_number: 115,
        top_side: 7,
        right_side: 12,
        bottom_side: 10,
        left_side: 11,
    },
    Piece {
        piece_number: 116,
        top_side: 12,
        right_side: 11,
        bottom_side: 10,
        left_side: 11,
    },
    Piece {
        piece_number: 117,
        top_side: 22,
        right_side: 16,
        bottom_side: 10,
        left_side: 11,
    },
    Piece {
        piece_number: 118,
        top_side: 3,
        right_side: 21,
        bottom_side: 10,
        left_side: 19,
    },
    Piece {
        piece_number: 119,
        top_side: 16,
        right_side: 12,
        bottom_side: 10,
        left_side: 7,
    },
    Piece {
        piece_number: 120,
        top_side: 8,
        right_side: 22,
        bottom_side: 10,
        left_side: 15,
    },
    Piece {
        piece_number: 121,
        top_side: 14,
        right_side: 22,
        bottom_side: 10,
        left_side: 4,
    },
    Piece {
        piece_number: 122,
        top_side: 6,
        right_side: 16,
        bottom_side: 10,
        left_side: 20,
    },
    Piece {
        piece_number: 123,
        top_side: 14,
        right_side: 19,
        bottom_side: 10,
        left_side: 20,
    },
    Piece {
        piece_number: 124,
        top_side: 20,
        right_side: 15,
        bottom_side: 10,
        left_side: 20,
    },
    Piece {
        piece_number: 125,
        top_side: 12,
        right_side: 22,
        bottom_side: 10,
        left_side: 8,
    },
    Piece {
        piece_number: 126,
        top_side: 21,
        right_side: 15,
        bottom_side: 10,
        left_side: 8,
    },
    Piece {
        piece_number: 127,
        top_side: 14,
        right_side: 6,
        bottom_side: 10,
        left_side: 16,
    },
    Piece {
        piece_number: 128,
        top_side: 19,
        right_side: 21,
        bottom_side: 10,
        left_side: 16,
    },
    Piece {
        piece_number: 129,
        top_side: 4,
        right_side: 3,
        bottom_side: 10,
        left_side: 16,
    },
    Piece {
        piece_number: 130,
        top_side: 20,
        right_side: 8,
        bottom_side: 10,
        left_side: 16,
    },
    Piece {
        piece_number: 131,
        top_side: 6,
        right_side: 20,
        bottom_side: 10,
        left_side: 21,
    },
    Piece {
        piece_number: 132,
        top_side: 12,
        right_side: 14,
        bottom_side: 10,
        left_side: 21,
    },
    Piece {
        piece_number: 133,
        top_side: 14,
        right_side: 16,
        bottom_side: 10,
        left_side: 22,
    },
    Piece {
        piece_number: 134,
        top_side: 11,
        right_side: 4,
        bottom_side: 10,
        left_side: 22,
    },
    Piece {
        piece_number: 135,
        top_side: 4,
        right_side: 3,
        bottom_side: 10,
        left_side: 22,
    },
    Piece {
        piece_number: 136,
        top_side: 16,
        right_side: 20,
        bottom_side: 10,
        left_side: 22,
    },
    Piece {
        piece_number: 137,
        top_side: 20,
        right_side: 7,
        bottom_side: 18,
        left_side: 18,
    },
    Piece {
        piece_number: 138,
        top_side: 6,
        right_side: 3,
        bottom_side: 18,
        left_side: 6,
    },
    Piece {
        piece_number: 139,
        top_side: 6,
        right_side: 11,
        bottom_side: 18,
        left_side: 6,
    },
    Piece {
        piece_number: 140,
        top_side: 6,
        right_side: 12,
        bottom_side: 18,
        left_side: 6,
    },
    Piece {
        piece_number: 141,
        top_side: 19,
        right_side: 21,
        bottom_side: 18,
        left_side: 6,
    },
    Piece {
        piece_number: 142,
        top_side: 15,
        right_side: 6,
        bottom_side: 18,
        left_side: 6,
    },
    Piece {
        piece_number: 143,
        top_side: 16,
        right_side: 12,
        bottom_side: 18,
        left_side: 6,
    },
    Piece {
        piece_number: 144,
        top_side: 21,
        right_side: 21,
        bottom_side: 18,
        left_side: 6,
    },
    Piece {
        piece_number: 145,
        top_side: 3,
        right_side: 4,
        bottom_side: 18,
        left_side: 14,
    },
    Piece {
        piece_number: 146,
        top_side: 18,
        right_side: 12,
        bottom_side: 18,
        left_side: 3,
    },
    Piece {
        piece_number: 147,
        top_side: 18,
        right_side: 22,
        bottom_side: 18,
        left_side: 3,
    },
    Piece {
        piece_number: 148,
        top_side: 3,
        right_side: 14,
        bottom_side: 18,
        left_side: 3,
    },
    Piece {
        piece_number: 149,
        top_side: 15,
        right_side: 12,
        bottom_side: 18,
        left_side: 3,
    },
    Piece {
        piece_number: 150,
        top_side: 6,
        right_side: 11,
        bottom_side: 18,
        left_side: 19,
    },
    Piece {
        piece_number: 151,
        top_side: 4,
        right_side: 22,
        bottom_side: 18,
        left_side: 19,
    },
    Piece {
        piece_number: 152,
        top_side: 11,
        right_side: 11,
        bottom_side: 18,
        left_side: 7,
    },
    Piece {
        piece_number: 153,
        top_side: 11,
        right_side: 19,
        bottom_side: 18,
        left_side: 7,
    },
    Piece {
        piece_number: 154,
        top_side: 22,
        right_side: 16,
        bottom_side: 18,
        left_side: 7,
    },
    Piece {
        piece_number: 155,
        top_side: 7,
        right_side: 7,
        bottom_side: 18,
        left_side: 4,
    },
    Piece {
        piece_number: 156,
        top_side: 7,
        right_side: 12,
        bottom_side: 18,
        left_side: 4,
    },
    Piece {
        piece_number: 157,
        top_side: 22,
        right_side: 7,
        bottom_side: 18,
        left_side: 4,
    },
    Piece {
        piece_number: 158,
        top_side: 7,
        right_side: 16,
        bottom_side: 18,
        left_side: 20,
    },
    Piece {
        piece_number: 159,
        top_side: 8,
        right_side: 6,
        bottom_side: 18,
        left_side: 20,
    },
    Piece {
        piece_number: 160,
        top_side: 21,
        right_side: 21,
        bottom_side: 18,
        left_side: 8,
    },
    Piece {
        piece_number: 161,
        top_side: 6,
        right_side: 20,
        bottom_side: 18,
        left_side: 16,
    },
    Piece {
        piece_number: 162,
        top_side: 14,
        right_side: 20,
        bottom_side: 18,
        left_side: 16,
    },
    Piece {
        piece_number: 163,
        top_side: 15,
        right_side: 11,
        bottom_side: 18,
        left_side: 22,
    },
    Piece {
        piece_number: 164,
        top_side: 4,
        right_side: 16,
        bottom_side: 18,
        left_side: 22,
    },
    Piece {
        piece_number: 165,
        top_side: 3,
        right_side: 4,
        bottom_side: 6,
        left_side: 14,
    },
    Piece {
        piece_number: 166,
        top_side: 4,
        right_side: 8,
        bottom_side: 6,
        left_side: 14,
    },
    Piece {
        piece_number: 167,
        top_side: 3,
        right_side: 3,
        bottom_side: 6,
        left_side: 11,
    },
    Piece {
        piece_number: 168,
        top_side: 11,
        right_side: 15,
        bottom_side: 6,
        left_side: 19,
    },
    Piece {
        piece_number: 169,
        top_side: 19,
        right_side: 21,
        bottom_side: 6,
        left_side: 19,
    },
    Piece {
        piece_number: 170,
        top_side: 4,
        right_side: 8,
        bottom_side: 6,
        left_side: 7,
    },
    Piece {
        piece_number: 171,
        top_side: 20,
        right_side: 16,
        bottom_side: 6,
        left_side: 7,
    },
    Piece {
        piece_number: 172,
        top_side: 21,
        right_side: 11,
        bottom_side: 6,
        left_side: 7,
    },
    Piece {
        piece_number: 173,
        top_side: 15,
        right_side: 15,
        bottom_side: 6,
        left_side: 15,
    },
    Piece {
        piece_number: 174,
        top_side: 12,
        right_side: 20,
        bottom_side: 6,
        left_side: 15,
    },
    Piece {
        piece_number: 175,
        top_side: 7,
        right_side: 21,
        bottom_side: 6,
        left_side: 4,
    },
    Piece {
        piece_number: 176,
        top_side: 7,
        right_side: 19,
        bottom_side: 6,
        left_side: 12,
    },
    Piece {
        piece_number: 177,
        top_side: 14,
        right_side: 4,
        bottom_side: 6,
        left_side: 20,
    },
    Piece {
        piece_number: 178,
        top_side: 12,
        right_side: 16,
        bottom_side: 6,
        left_side: 8,
    },
    Piece {
        piece_number: 179,
        top_side: 8,
        right_side: 15,
        bottom_side: 6,
        left_side: 8,
    },
    Piece {
        piece_number: 180,
        top_side: 7,
        right_side: 16,
        bottom_side: 6,
        left_side: 16,
    },
    Piece {
        piece_number: 181,
        top_side: 11,
        right_side: 16,
        bottom_side: 6,
        left_side: 21,
    },
    Piece {
        piece_number: 182,
        top_side: 7,
        right_side: 11,
        bottom_side: 6,
        left_side: 21,
    },
    Piece {
        piece_number: 183,
        top_side: 19,
        right_side: 8,
        bottom_side: 14,
        left_side: 14,
    },
    Piece {
        piece_number: 184,
        top_side: 22,
        right_side: 7,
        bottom_side: 14,
        left_side: 3,
    },
    Piece {
        piece_number: 185,
        top_side: 19,
        right_side: 12,
        bottom_side: 14,
        left_side: 11,
    },
    Piece {
        piece_number: 186,
        top_side: 8,
        right_side: 8,
        bottom_side: 14,
        left_side: 11,
    },
    Piece {
        piece_number: 187,
        top_side: 21,
        right_side: 7,
        bottom_side: 14,
        left_side: 19,
    },
    Piece {
        piece_number: 188,
        top_side: 14,
        right_side: 21,
        bottom_side: 14,
        left_side: 7,
    },
    Piece {
        piece_number: 189,
        top_side: 3,
        right_side: 19,
        bottom_side: 14,
        left_side: 7,
    },
    Piece {
        piece_number: 190,
        top_side: 16,
        right_side: 19,
        bottom_side: 14,
        left_side: 7,
    },
    Piece {
        piece_number: 191,
        top_side: 3,
        right_side: 3,
        bottom_side: 14,
        left_side: 15,
    },
    Piece {
        piece_number: 192,
        top_side: 15,
        right_side: 20,
        bottom_side: 14,
        left_side: 15,
    },
    Piece {
        piece_number: 193,
        top_side: 11,
        right_side: 7,
        bottom_side: 14,
        left_side: 4,
    },
    Piece {
        piece_number: 194,
        top_side: 21,
        right_side: 11,
        bottom_side: 14,
        left_side: 12,
    },
    Piece {
        piece_number: 195,
        top_side: 21,
        right_side: 22,
        bottom_side: 14,
        left_side: 12,
    },
    Piece {
        piece_number: 196,
        top_side: 22,
        right_side: 15,
        bottom_side: 14,
        left_side: 12,
    },
    Piece {
        piece_number: 197,
        top_side: 11,
        right_side: 22,
        bottom_side: 14,
        left_side: 20,
    },
    Piece {
        piece_number: 198,
        top_side: 19,
        right_side: 8,
        bottom_side: 14,
        left_side: 20,
    },
    Piece {
        piece_number: 199,
        top_side: 20,
        right_side: 20,
        bottom_side: 14,
        left_side: 20,
    },
    Piece {
        piece_number: 200,
        top_side: 19,
        right_side: 3,
        bottom_side: 14,
        left_side: 8,
    },
    Piece {
        piece_number: 201,
        top_side: 21,
        right_side: 8,
        bottom_side: 14,
        left_side: 16,
    },
    Piece {
        piece_number: 202,
        top_side: 22,
        right_side: 7,
        bottom_side: 14,
        left_side: 16,
    },
    Piece {
        piece_number: 203,
        top_side: 12,
        right_side: 19,
        bottom_side: 14,
        left_side: 21,
    },
    Piece {
        piece_number: 204,
        top_side: 12,
        right_side: 8,
        bottom_side: 14,
        left_side: 21,
    },
    Piece {
        piece_number: 205,
        top_side: 16,
        right_side: 3,
        bottom_side: 14,
        left_side: 21,
    },
    Piece {
        piece_number: 206,
        top_side: 22,
        right_side: 21,
        bottom_side: 14,
        left_side: 21,
    },
    Piece {
        piece_number: 207,
        top_side: 22,
        right_side: 7,
        bottom_side: 3,
        left_side: 3,
    },
    Piece {
        piece_number: 208,
        top_side: 19,
        right_side: 22,
        bottom_side: 3,
        left_side: 11,
    },
    Piece {
        piece_number: 209,
        top_side: 8,
        right_side: 15,
        bottom_side: 3,
        left_side: 11,
    },
    Piece {
        piece_number: 210,
        top_side: 11,
        right_side: 19,
        bottom_side: 3,
        left_side: 7,
    },
    Piece {
        piece_number: 211,
        top_side: 16,
        right_side: 15,
        bottom_side: 3,
        left_side: 7,
    },
    Piece {
        piece_number: 212,
        top_side: 3,
        right_side: 16,
        bottom_side: 3,
        left_side: 15,
    },
    Piece {
        piece_number: 213,
        top_side: 8,
        right_side: 8,
        bottom_side: 3,
        left_side: 4,
    },
    Piece {
        piece_number: 214,
        top_side: 3,
        right_side: 20,
        bottom_side: 3,
        left_side: 12,
    },
    Piece {
        piece_number: 215,
        top_side: 4,
        right_side: 22,
        bottom_side: 3,
        left_side: 12,
    },
    Piece {
        piece_number: 216,
        top_side: 22,
        right_side: 21,
        bottom_side: 3,
        left_side: 12,
    },
    Piece {
        piece_number: 217,
        top_side: 19,
        right_side: 15,
        bottom_side: 3,
        left_side: 20,
    },
    Piece {
        piece_number: 218,
        top_side: 4,
        right_side: 12,
        bottom_side: 3,
        left_side: 16,
    },
    Piece {
        piece_number: 219,
        top_side: 11,
        right_side: 4,
        bottom_side: 3,
        left_side: 21,
    },
    Piece {
        piece_number: 220,
        top_side: 11,
        right_side: 16,
        bottom_side: 3,
        left_side: 22,
    },
    Piece {
        piece_number: 221,
        top_side: 21,
        right_side: 21,
        bottom_side: 3,
        left_side: 22,
    },
    Piece {
        piece_number: 222,
        top_side: 21,
        right_side: 22,
        bottom_side: 3,
        left_side: 22,
    },
    Piece {
        piece_number: 223,
        top_side: 12,
        right_side: 22,
        bottom_side: 11,
        left_side: 11,
    },
    Piece {
        piece_number: 224,
        top_side: 20,
        right_side: 7,
        bottom_side: 11,
        left_side: 11,
    },
    Piece {
        piece_number: 225,
        top_side: 16,
        right_side: 15,
        bottom_side: 11,
        left_side: 11,
    },
    Piece {
        piece_number: 226,
        top_side: 19,
        right_side: 15,
        bottom_side: 11,
        left_side: 7,
    },
    Piece {
        piece_number: 227,
        top_side: 12,
        right_side: 12,
        bottom_side: 11,
        left_side: 7,
    },
    Piece {
        piece_number: 228,
        top_side: 19,
        right_side: 8,
        bottom_side: 11,
        left_side: 4,
    },
    Piece {
        piece_number: 229,
        top_side: 7,
        right_side: 22,
        bottom_side: 11,
        left_side: 20,
    },
    Piece {
        piece_number: 230,
        top_side: 16,
        right_side: 8,
        bottom_side: 11,
        left_side: 20,
    },
    Piece {
        piece_number: 231,
        top_side: 12,
        right_side: 20,
        bottom_side: 11,
        left_side: 8,
    },
    Piece {
        piece_number: 232,
        top_side: 12,
        right_side: 21,
        bottom_side: 11,
        left_side: 8,
    },
    Piece {
        piece_number: 233,
        top_side: 19,
        right_side: 20,
        bottom_side: 19,
        left_side: 19,
    },
    Piece {
        piece_number: 234,
        top_side: 16,
        right_side: 4,
        bottom_side: 19,
        left_side: 7,
    },
    Piece {
        piece_number: 235,
        top_side: 7,
        right_side: 4,
        bottom_side: 19,
        left_side: 4,
    },
    Piece {
        piece_number: 236,
        top_side: 7,
        right_side: 20,
        bottom_side: 19,
        left_side: 4,
    },
    Piece {
        piece_number: 237,
        top_side: 12,
        right_side: 15,
        bottom_side: 19,
        left_side: 4,
    },
    Piece {
        piece_number: 238,
        top_side: 4,
        right_side: 16,
        bottom_side: 19,
        left_side: 12,
    },
    Piece {
        piece_number: 239,
        top_side: 15,
        right_side: 22,
        bottom_side: 19,
        left_side: 20,
    },
    Piece {
        piece_number: 240,
        top_side: 21,
        right_side: 15,
        bottom_side: 19,
        left_side: 20,
    },
    Piece {
        piece_number: 241,
        top_side: 7,
        right_side: 21,
        bottom_side: 19,
        left_side: 8,
    },
    Piece {
        piece_number: 242,
        top_side: 4,
        right_side: 21,
        bottom_side: 19,
        left_side: 8,
    },
    Piece {
        piece_number: 243,
        top_side: 15,
        right_side: 12,
        bottom_side: 7,
        left_side: 15,
    },
    Piece {
        piece_number: 244,
        top_side: 20,
        right_side: 8,
        bottom_side: 7,
        left_side: 15,
    },
    Piece {
        piece_number: 245,
        top_side: 22,
        right_side: 20,
        bottom_side: 7,
        left_side: 4,
    },
    Piece {
        piece_number: 246,
        top_side: 16,
        right_side: 22,
        bottom_side: 7,
        left_side: 21,
    },
    Piece {
        piece_number: 247,
        top_side: 21,
        right_side: 22,
        bottom_side: 15,
        left_side: 15,
    },
    Piece {
        piece_number: 248,
        top_side: 12,
        right_side: 4,
        bottom_side: 15,
        left_side: 4,
    },
    Piece {
        piece_number: 249,
        top_side: 4,
        right_side: 21,
        bottom_side: 15,
        left_side: 12,
    },
    Piece {
        piece_number: 250,
        top_side: 16,
        right_side: 21,
        bottom_side: 15,
        left_side: 20,
    },
    Piece {
        piece_number: 251,
        top_side: 22,
        right_side: 8,
        bottom_side: 4,
        left_side: 4,
    },
    Piece {
        piece_number: 252,
        top_side: 8,
        right_side: 12,
        bottom_side: 4,
        left_side: 12,
    },
    Piece {
        piece_number: 253,
        top_side: 16,
        right_side: 20,
        bottom_side: 12,
        left_side: 8,
    },
    Piece {
        piece_number: 254,
        top_side: 21,
        right_side: 16,
        bottom_side: 20,
        left_side: 16,
    },
    Piece {
        piece_number: 255,
        top_side: 16,
        right_side: 22,
        bottom_side: 20,
        left_side: 22,
    },
    Piece {
        piece_number: 256,
        top_side: 21,
        right_side: 22,
        bottom_side: 8,
        left_side: 22,
    },
];
